"""update table

Revision ID: 1d165d610c14
Revises: 
Create Date: 2026-02-02 17:16:58.887992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d165d610c14'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('timer_started_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('tasks', 'time_spent',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tasks', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tasks', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tasks', 'time_spent',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('tasks', 'timer_started_at')
    # ### end Alembic commands ###
